# coding: utf-8
CATEGORIES = [
    # 엔터테인먼트&예술
    {'name': '문학&책', 'directoryNo': 5, 'activeDirectorySeq': 1,
     'index-name': 'entertainment&arts/literature&book', 'class': 0},
    {'name': '영화', 'directoryNo': 6, 'activeDirectorySeq': 1,
     'index-name': 'entertainment&arts/movie', 'class': 1},
    {'name': '미술&디자인', 'directoryNo': 8, 'activeDirectorySeq': 1,
     'index-name': 'entertainment&arts/art&design', 'class': 2},
    {'name': '공연&전시', 'directoryNo': 7, 'activeDirectorySeq': 1,
     'index-name': 'entertainment&arts/performance&exhibit', 'class': 3},
    {'name': '음악', 'directoryNo': 11, 'activeDirectorySeq': 1,
     'index-name': 'entertainment&arts/music', 'class': 4},
    {'name': '드라마', 'directoryNo': 9, 'activeDirectorySeq': 1,
     'index-name': 'entertainment&arts/drama', 'class': 5},
    {'name': '스타&연예인', 'directoryNo': 12, 'activeDirectorySeq': 1,
     'index-name': 'entertainment&arts/star&entertainer', 'class': 6},
    {'name': '만화&애니', 'directoryNo': 13, 'activeDirectorySeq': 1,
     'index-name': 'entertainment&arts/cartoon&animation', 'class': 7},
    {'name': '방송', 'directoryNo': 10, 'activeDirectorySeq': 1,
     'index-name': 'entertainment&arts/broadcasting', 'class': 8},

    # 생활&노하우&쇼핑
    {'name': '일상&생각', 'directoryNo': 14, 'activeDirectorySeq': 2,
     'index-name': 'life&knowhow&shopping/daily&thoughts', 'class': 9},
    {'name': '육아&결혼', 'directoryNo': 15, 'activeDirectorySeq': 2,
     'index-name': 'life&knowhow&shopping/childrearing&marriage', 'class': 10},
    {'name': '애완&반려동물', 'directoryNo': 16, 'activeDirectorySeq': 2,
     'index-name': 'life&knowhow&shopping/pets', 'class': 11},
    {'name': '패션&미용', 'directoryNo': 18, 'activeDirectorySeq': 2,
     'index-name': 'life&knowhow&shopping/fashion&beauty', 'class': 12},
    {'name': '인테리어&DIY', 'directoryNo': 19, 'activeDirectorySeq': 2,
     'index-name': 'life&knowhow&shopping/interiordesign&diy', 'class': 13},
    {'name': '요리&레시피', 'directoryNo': 20, 'activeDirectorySeq': 2,
     'index-name': 'life&knowhow&shopping/cook&recipe', 'class': 14},
    {'name': '상품리뷰', 'directoryNo': 21, 'activeDirectorySeq': 2,
     'index-name': 'life&knowhow&shopping/itemreview', 'class': 15},
    {'name': '원예&재배', 'directoryNo': 36, 'activeDirectorySeq': 2,
     'index-name': 'life&knowhow&shopping/gardencultivation', 'class': 16},

    # 취미&여가&여행
    {'name': '게임', 'directoryNo': 22, 'activeDirectorySeq': 3,
     'index-name': 'hobby&leisure&trip/game', 'class': 17},
    {'name': '스포츠', 'directoryNo': 23, 'activeDirectorySeq': 3,
     'index-name': 'hobby&leisure&trip/sports', 'class': 18},
    {'name': '사진', 'directoryNo': 24, 'activeDirectorySeq': 3,
     'index-name': 'hobby&leisure&trip/photo', 'class': 19},
    {'name': '자동차', 'directoryNo': 25, 'activeDirectorySeq': 3,
     'index-name': 'hobby&leisure&trip/automobile', 'class': 20},
    {'name': '취미', 'directoryNo': 26, 'activeDirectorySeq': 3,
     'index-name': 'hobby&leisure&trip/hobby', 'class': 21},
    {'name': '국내여행', 'directoryNo': 27, 'activeDirectorySeq': 3,
     'index-name': 'hobby&leisure&trip/domestictrip', 'class': 22},
    {'name': '해외여행', 'directoryNo': 28, 'activeDirectorySeq': 3,
     'index-name': 'hobby&leisure&trip/overseastrip', 'class': 23},
    {'name': '맛집', 'directoryNo': 29, 'activeDirectorySeq': 3,
     'index-name': 'hobby&leisure&trip/restaurant', 'class': 24},

    # 지식&동향
    {'name': 'IT&컴퓨터', 'directoryNo': 30, 'activeDirectorySeq': 4,
     'index-name': 'knowledge&trend/IT&computer', 'class': 25},
    {'name': '사회&정치', 'directoryNo': 31, 'activeDirectorySeq': 4,
     'index-name': 'knowledge&trend/society&politics', 'class': 26},
    {'name': '건강&의학', 'directoryNo': 32, 'activeDirectorySeq': 4,
     'index-name': 'knowledge&trend/health&medicine', 'class': 27},
    {'name': '비지니스&경제', 'directoryNo': 33, 'activeDirectorySeq': 4,
     'index-name': 'knowledge&trend/business&economy', 'class': 28},
    {'name': '어학&외국어', 'directoryNo': 35, 'activeDirectorySeq': 4,
     'index-name': 'knowledge&trend/language', 'class': 29},
    {'name': '교육&학문', 'directoryNo': 34, 'activeDirectorySeq': 4,
     'index-name': 'knowledge&trend/education&study', 'class': 30}
]